version: '3'
services:
  php-cli:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./app:/app
    command: sh -c "composer install --no-interaction && php"
    tty: true
